### ISSUE TITLE
Broken due to Content Security Policy on Budibase Cloud

### ISSUE THREAD

**Issue by JayP718** [shogunpurple/budibase-component-microphone#2]
hi,

Awesome plugin. Do you mind if I fork (Not sure what license this is published with) to create a similar plugin to allow it to be used on forms with Budibase attachments? I think there's another issue raised so might be helpful to them as well. Don't want to create a pull request to mess with existing implementations.

Also it seems like this plugin doesn't work in the cloud due to a content security policy
<img width="611" alt="image" src="https://user-images.githubusercontent.com/42209052/210647135-2e5877cf-c284-4050-8079-012cc31a9717.png">

**Comment by shogunpurple** [comment]
Hi @JayP718 - You may fork as you wish, or if it's something that you think may benefit everyone it may be worth a PR into this repo.
